function extractVideoId(input) {
  const value = (input || "").trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(value)) return value;
  try {
    const u = new URL(value);
    if (u.hostname === "youtu.be") return u.pathname.split("/").filter(Boolean)[0] || null;
    if (u.hostname.endsWith("youtube.com")) {
      if (u.searchParams.get("v")) return u.searchParams.get("v");
      const parts = u.pathname.split("/").filter(Boolean);
      const marker = parts.findIndex((p) => ["shorts", "embed", "live"].includes(p));
      if (marker >= 0 && parts[marker + 1]) return parts[marker + 1];
    }
  } catch {}
  return null;
}

function extractJsonArray(source, marker) {
  const markerPos = source.indexOf(marker);
  if (markerPos < 0) return null;
  const start = source.indexOf("[", markerPos + marker.length);
  if (start < 0) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < source.length; i++) {
    const ch = source[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }
  return null;
}

function cleanText(value) {
  return (value || "")
    .replace(/\n/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function fetchTracks(videoId) {
  const watchUrl = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`;
  const res = await fetch(watchUrl, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; Bankr-x402-Transcript/1.0)",
      "Accept-Language": "en-US,en;q=0.9"
    }
  });
  if (!res.ok) throw new Error(`YouTube watch page returned HTTP ${res.status}`);
  const html = await res.text();
  const raw = extractJsonArray(html, '"captionTracks":');
  if (!raw) return [];
  try {
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

function selectTrack(tracks, preferred) {
  if (!tracks.length) return null;
  if (!preferred) return tracks.find((t) => t.kind !== "asr") || tracks[0];
  const wanted = preferred.toLowerCase();
  return (
    tracks.find((t) => (t.languageCode || "").toLowerCase() === wanted && t.kind !== "asr") ||
    tracks.find((t) => (t.languageCode || "").toLowerCase() === wanted) ||
    tracks.find((t) => (t.languageCode || "").toLowerCase().startsWith(`${wanted}-`) && t.kind !== "asr") ||
    tracks.find((t) => (t.languageCode || "").toLowerCase().startsWith(`${wanted}-`)) ||
    tracks.find((t) => t.kind !== "asr") ||
    tracks[0]
  );
}

async function fetchTranscript(track) {
  const separator = track.baseUrl.includes("?") ? "&" : "?";
  const res = await fetch(`${track.baseUrl}${separator}fmt=json3`, {
    headers: { "User-Agent": "Mozilla/5.0 (compatible; Bankr-x402-Transcript/1.0)" }
  });
  if (!res.ok) throw new Error(`Caption track returned HTTP ${res.status}`);
  const data = await res.json();
  const segments = [];
  for (const event of data.events || []) {
    if (!event.segs) continue;
    const text = cleanText(event.segs.map((s) => s.utf8 || "").join(""));
    if (!text) continue;
    segments.push({
      startMs: Number(event.tStartMs || 0),
      durationMs: Number(event.dDurationMs || 0),
      text
    });
  }
  return segments;
}

export default async function handler(req) {
  if (req.method !== "GET") {
    return Response.json({ error: "GET required" }, { status: 405 });
  }

  const url = new URL(req.url);
  const video = url.searchParams.get("video") || url.searchParams.get("url") || url.searchParams.get("videoId");
  const language = url.searchParams.get("language") || url.searchParams.get("lang") || undefined;
  const videoId = extractVideoId(video);

  if (!videoId) {
    return Response.json({ error: "Provide a valid YouTube URL or 11-character video ID in ?video=" }, { status: 400 });
  }

  try {
    const tracks = await fetchTracks(videoId);
    if (!tracks.length) {
      return Response.json({ error: "No captions are available for this video", videoId }, { status: 404 });
    }

    const track = selectTrack(tracks, language);
    const segments = await fetchTranscript(track);
    if (!segments.length) {
      return Response.json({ error: "Caption track was found but contained no transcript text", videoId }, { status: 502 });
    }

    return {
      videoId,
      language: track.languageCode || null,
      languageName: track.name?.simpleText || track.languageCode || null,
      isAutoGenerated: track.kind === "asr",
      text: segments.map((s) => s.text).join(" "),
      segments,
      availableLanguages: tracks.map((t) => ({
        language: t.languageCode || null,
        name: t.name?.simpleText || t.languageCode || null,
        isAutoGenerated: t.kind === "asr"
      }))
    };
  } catch (error) {
    return Response.json({ error: "Failed to retrieve transcript", detail: String(error?.message || error), videoId }, { status: 502 });
  }
}
